name = "cf_ai_reverie"
main = "workers/index.ts"
compatibility_date = "2024-11-20"
workers_dev = true

[assets]
directory = "./pages/public"

[ai]
binding = "AI"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "reverie-r2"

[[kv_namespaces]]
binding = "CACHE"
id = "de6ced93bcda4e57820c9c0a564536ae"
preview_id = "72a6c38c9a5d4d029c866846e29498ab"

[[durable_objects.bindings]]
name = "SESSION_DO"
class_name = "SessionDO"

[[migrations]]
tag = "v1"
new_classes = ["SessionDO"]

[vars]
APP_NAME = "Reverie"
